echo2_integration_test.cc
echo2_server.json

This change corresponds to changes in https://github.com/lyft/envoy/pull/883 to allow for Ipv6 parameterized integration testing. In https://github.com/lyft/envoy/pull/883, we SetUp the test_server for each test rather than once in SetUpTestCase.

Parameterize echo listener address

---

WORKSPACE
echo2_integration_test.cc
echo2_server.json

This PR updates the echo2 integration test to reflect changes made in the envoy repo. 
We also parameterize the admin address.

test: update echo2 test

---

BUILD

BUILD now refs envoy's envoy_main_entry_lib instead of envoy_main_lib.  Updated git submodule envoy ref to tip of  master.   See issue #11

Fix build, update envoy git submodule ref

---

BUILD
WORKSPACE
envoy_binary_test.sh

The envoy-filter-example CI did not actually verify that a runnable
binary was built since it only ran a test. A change in Envoy resulted in
the binary build from the envoy-filter-example becoming broken.
The submodule hash is updated as part of this commit.  The WORKSPACE
file is modified to include references to the api dependencies added
since the last submodule hash update.
After this is merged a commit to Envoy will update the filter-example
hash for CI to include this commit, and modify do_ci.sh to run this
new test.

Improve CI testing.

---

http-filter-example/BUILD
http-filter-example/envoy.conf
http-filter-example/http_filter_integration_test.cc

I fixed the tests in the http filter example by extending HttpIntegrationTest instead, I had issues with the envoy config writing to `/dev/stdout` so i had to send it to `/dev/null` on OSX
This was the error 
http-filter-example/envoy.conf.with.ports.json': unable to open file '/dev/stdout': Permission denied

fixed tests by using HttpIntegrationTest integration instead

---

BUILD
echo2_integration_test.cc
echo2_server.yaml

Bumping Envoy to 7aa956f1eb17454240646e55e13caf72db850af2
Porting the echo2 integration test to the v2 API.
Leaving the v1 json file in situ (unused) for legacy reference.

Porting the echo2 integration test to the v2 API.

---

http-filter-example/BUILD
http-filter-example/http_filter.cc
http-filter-example/http_filter.h
http-filter-example/http_filter.proto
http-filter-example/http_filter_config.cc
http-filter-example/http_filter_integration_test.cc

This patch exhibits an example of adding a .proto config to the http-filter-example. 
Closes #31.
Signed-off-by: Dhi Aurrahman <dio@hooq.tv>

Add a proto config example for http-filter-example

---

echo2_integration_test.cc

The integration test was broken by a recent envoy change, but it seems that CI didn't try to rebuild the filter example until I tried to update it.
This change goes along with https://github.com/envoyproxy/envoy/commit/97b69ce6a507471180c0585b6742c627962b433b

Fix integration test

---

http-filter-example/BUILD

Due to API restructure.
Signed-off-by: Dhi Aurrahman <dio@rockybars.com>

Fix http-filter-example integration test compilation error

---

http-filter-example/BUILD

This patch removes `http_filter_integration_test` dep to @envoy_api's
`http_connection_manager` since the codec client type is decided inside
the `HttpIntegrationTest` class.
Signed-off-by: Dhi Aurrahman <dio@rockybars.com>

Remove dep to @envoy_api http_connection_manager

---

http-filter-example/README.md

- Use fixed commit versions to avoid wrong references due to later
master branch modifications
- Fix broken ref for [removed](8d68ffe819f2599) `envoy.conf`
Signed-off-by: embs <embs@cin.ufpe.br>

http-filter-example: Fix README's references

---

echo2_config.cc
echo2_server.yaml

This patch fixes the `echo2` network filter integration test. By actually testing `echo2` instead of `envoy.echo` filter.
Signed-off-by: Dhi Aurrahman <dio@rockybars.com>

Fix echo2 test

---

http-filter-example/BUILD
http-filter-example/http_filter.cc
http-filter-example/http_filter.h

This change updates the HTTP example filter to work with the latest `envoyproxy/envoy` master, which had a recent refactoring of include files.
Signed-off-by: Brian Pane <bpane@pinterest.com>

Fix compilation with latest Envoy master

---

ci/do_ci.sh

Seems mostly harmless given what we test in this repo.
Signed-off-by: Harvey Tuch <htuch@google.com>

ci: disable IPv6 tests due to CircleCI lack of support.

---

echo2_config.cc
http-filter-example/http_filter_config.cc

No functional changes, missed in previous commit.

cleanup: move filter wrapper into Http namespace.

---

.clang-format
http-filter-example/http_filter_config.cc

This commit fixes the following compilation error:
```
ERROR: /Users/marpaia/git/envoy-filter-example/http-filter-example/BUILD:37:1: C++ compilation of rule '//http-filter-example:http_filter_config' failed (Exit 1)
http-filter-example/http_filter_config.cc:49:14: error: lambda capture 'context' is not used [-Werror,-Wunused-lambda-capture]
return [&context, config](Http::FilterChainFactoryCallbacks& callbacks) -> void {
^
1 error generated.
Target //http-filter-example:envoy failed to build
```
This commit also adds Envoy's `.clang-format` file so that editors don't incorrectly format C++.

Fix compile error due to unused lambda capture

---

WORKSPACE
http-filter-example/http_filter_integration_test.cc

* Fix WORKSPACE issue in
https://github.com/envoyproxy/envoy-filter-example/issues/61.
* Also seems to have regressed due to TimeSystem and other integration
test API  changes.
Fixes #61 
Signed-off-by: Harvey Tuch <htuch@google.com>

build/test: fix various build/test failures.

---

.bazelrc
tools/bazel.rc

This is future-proofing, since %workspace%/tools/bazel.rc won't be
automatically processed starting with Bazel 0.19 (October 2018).
Signed-off-by: Piotr Sikora <piotrsikora@google.com>

bazel: add .bazelrc and use Bazel's import instead of symlinking.

---

echo2_server.yaml

Since [`cluster.hosts` is deprecated](https://github.com/envoyproxy/envoy/issues/4618), we use `cluster.load_assignment` to declare the workloads. 
Signed-off-by: Dhi Aurrahman <dio@tetrate.io>

Use load_assignment instead of hosts

---

WORKSPACE

Builds broke as of https://github.com/envoyproxy/envoy/commit/7fa55135828dc8d93c6eee6f363534afa5cb3484
Original PR in envoy: https://github.com/envoyproxy/envoy/pull/5218
It seems like this won't be needed once the foreign_cc definitions are moved into `envoy_dependencies`?

build: add foreign_cc rules

---

WORKSPACE

Make `WORKSPACE` support the commit that updates to rules_go 0.17.1:
https://github.com/envoyproxy/envoy/commit/fdbbe6edaaa971f6f095a2afffbf521fe9176cee
Risk Level: Low
Testing: `bazel test //:echo2_integration_test`
Docs Changes: N/A
Release Notes: N/A
Fixes #82
Signed-off-by: Tal Nordan <github@talnordan.com>

dependencies: update go_rules_dependencies

---

http-filter-example/http_filter_integration_test.cc

Replace the HeaderString::c_str() API with getStringView() and EXPECT_STREQ with EXPECT_EQ for string objects comparision
Docs Changes: None
Release Notes: None
Fixes #87

test: Fix http integration test

---

echo2_server.json
echo2_server.yaml

Fixes two config issues when starting envoy:
1. `echo2_server.yaml`: 
```
rchapman@x1:~/src/envoy-filter-example$ ./bazel-bin/envoy --config-path echo2_server.yaml
[2019-06-23 21:51:26.463][9476][info][main] [external/envoy/source/server/server.cc:234] initializing epoch 0 (hot restart version=11.104)
[...]
[2019-06-23 21:51:26.484][9476][critical][main] [external/envoy/source/server/server.cc:91] error initializing configuration 'echo2_server.yaml': Field 'connect_timeout' is missing in: name: "cluster_0"
[...]
```
2. `echo2_server.json`:
```
rchapman@x1:~/src/envoy-filter-example$ ./bazel-bin/envoy --config-path echo2_server.json
[2019-06-23 21:52:49.193][9542][info][main] [external/envoy/source/server/server.cc:234] initializing epoch 0 (hot restart version=11.104)
[...]
[2019-06-23 …
```

Fix config file issues

---

echo2_integration_test.cc
http-filter-example/http_filter_integration_test.cc

As part of https://github.com/envoyproxy/envoy/pull/7426 (upgrading the current version of Googletest in use by Envoy), all uses of INSTANTIATE_TEST_CASE_P need to be changed to INSTANTIATE_TEST_SUITE_P.  This does so for the envoy-filter-example, which is used in the automatic testing of the Envoy repository.

Change INSTANTIATE_TEST_CASE_P to INSTANTIATE_TEST_SUITE_P

---

http-filter-example/http_filter_config.cc

`downcastAndValidate` takes an additional parameter now. This fixes the build.

Add messageValidationVisitor() to downcastAndValidate

---

http-filter-example/BUILD

Update api_proto_library to api_proto_package in BUILD file of http-filter-example to adapt new version api proto build system.
Signed-off-by: wbpcode <comems@msn.com>

update api_proto_library to api_proto_package in BUILD

---

echo2_config.cc
http-filter-example/http_filter_config.cc

In https://github.com/envoyproxy/envoy/pull/8749 the v1 interface methods were made optional with a default implementation because this repository still consumed those methods using `override`. Once these are cleared out, we can fully remove the v1 methods from the main codebase.
Built the change locally and verified the tests pass.
Signed-off-by: Derek Argueta <dereka@pinterest.com>

api: remove v1 methods

---

.bazelversion

- Add `.bazelversion` to enable us to use `bazelisk`.
- It's a just symlink to submodule envoy's `.bazelversion` to use same version.
According to [Envoy's build instruction](https://github.com/envoyproxy/envoy/blob/master/bazel/README.md), we should use `bazelisk` to avoid Bazel compatibility issues.
Actually, it seems that `bazel build //:envoy` fails with latest Bazel `1.0.0`.

Add .bazelversion

---

http-filter-example/http_filter_integration_test.cc

Use the default upstream connection timeout for this test in
the hopes that it resolves the test flake.
Risk Level: low
Fixes: envoyproxy/envoy#9948
Signed-off-by: Stephan Zuercher <zuercher@gmail.com>

test flake: remove low timeout on test harness

---

http-filter-example/http_filter_config.cc

Rename Envoy::Server::Configuration::HttpSampleDecoderFilterConfig to Envoy::Server::Configuration::HttpSampleDecoderFilterConfigFactory to reduce confusion with Envoy::Http::HttpSampleDecoderFilterConfig
Glad to modify commit message to what works best

Rename to HttpSampleDecoderFilterConfigFactory

---

README.md

It should be "envoy_main_entry_lib" instead of "envoy_main_lib" based on the BUILD file. see issue https://github.com/envoyproxy/envoy-filter-example/issues/123

fix a minor error in the README

---

echo2_config.cc

This pr should make https://github.com/envoyproxy/envoy/pull/15803 pass the ci which relies on this repo.

config: support determine terminal filter at runtime

---

.bazelrc

Unfortunately this setting coming from envoy's bazelrc isn't smart
enough to be WORKSPACE relative, so we have to override it with the
right path.
Fixes https://github.com/envoyproxy/envoy-filter-example/issues/155
Signed-off-by: Keith Smiley <keithbsmiley@gmail.com>

bazel: fix platform_mappings

---

.github/workflows/envoy-sync.yaml
ci/sync_envoy.sh

Currently Envoy CI uses an SSH key with all powers to sync this repo by pushing to it
This is not optimally secure, and furthermore this pattern regularly causes Envoy CI to flake racing to checkout/push downstream repos.
I have created an app with just wf trigger permissions and added it to this repo
This PR adds a workflow that can be triggered by the app to sync Envoy by pulling from it

ci: Add sync workflow
