echo2_integration_test.cc

Updates echo2 integration test to match onging changes in https://github.com/lyft/envoy/pull/1036 .

test: update echo 2 test

---

WORKSPACE
echo2.cc
echo2.h
echo2_config.cc
echo2_integration_test.cc
echo2_server.json

Also update envoy submodule to current master. I need to use envoy-ci branch
for the registration refactor I am working on.

Update master from envoy-ci branch

---

BUILD
echo2_config.cc

I've tested this branch against the static registration change in envoy.  @mattklein123 Since I'm not able to create an upstream branch, I assume I should just PR this and someone with permissions can create a non-master branch and merge this there?

Updated registration interface to match static registration PR in envoy

---

README.md

readme: fix @envoy path in test instructions.

---

http-filter-example/http_filter.cc

envoy: bump to d123890.

---

WORKSPACE

Also name the workspace something more accurate (`@envoy` is the main
repo).

Update the filter example WORKSPACE to remove `repository` param.

---

echo2.cc
echo2.h

Signed-off-by: Greg Greenway <ggreenway@apple.com>

Modify to implement new half-close interfaces.

---

.circleci/config.yml
ci/do_ci.sh

This creates the initial build and test workflows for circleci.
Dependent upon #40 
Closes #37
Signed-off-by: <Nicholas Johns nicholas.a.johns5@gmail.com>

Build: create initial circleci project

---

echo2_config.cc

cleanup: move filter wrappers into Network namespace.

---

echo2_config.cc

Signed-off-by: Stephan Zuercher <stephan@turbinelabs.io>

cleanup: match NOT_IMPLEMENTED_GCOVR_EXCL_LINE change

---

echo2.cc

Removing ASSERT for safe landing of envoy/#3934

---

http-filter-example/http_filter_integration_test.cc

Fix an outdated test case for http filter

---

README.md

Signed-off-by: Venil Noronha <veniln@vmware.com>

Fix broken echo filter link in README

---

echo2_server.json

To go with https://github.com/envoyproxy/envoy/pull/5146

config: removing filter types

---

ci/do_ci.sh

Signed-off-by: Harvey Tuch <htuch@google.com>

ci: switch to clang to avoid CircleCI resource issues.

---

WORKSPACE

Signed-off-by: Lizan Zhou <lizan@tetrate.io>

build: update WORKSPACE

---

ci/do_ci.sh

Fix standalone CI (e.g. https://circleci.com/gh/envoyproxy/envoy-filter-example/4487)

ci: configure clang-8

---

WORKSPACE

Signed-off-by: Lizan Zhou <lizan@tetrate.io>

ci: update WORKSPACE from envoyproxy/envoy#7555

---

echo2_config.cc

echo: tagging echo2 as a terminal filter

---

echo2_integration_test.cc

Signed-off-by: Lizan Zhou <lizan@tetrate.io>

test: specify workspace in runfilesPath

---

echo2_config.cc
http-filter-example/http_filter_config.cc

Signed-off-by: Kuat Yessenov <kuat@google.com>

update filter name() method

---

echo2_config.cc

Needed for https://github.com/envoyproxy/envoy/pull/9581
Signed-off-by: Kuat Yessenov <kuat@google.com>

do not use empty for config

---

http-filter-example/http_filter.cc
http-filter-example/http_filter.h
http-filter-example/http_filter_integration_test.cc

To go with https://github.com/envoyproxy/envoy/pull/10081
Signed-off-by: Matt Klein <mklein@lyft.com>

http: fix types

---

echo2_integration_test.cc

To go with https://github.com/envoyproxy/envoy/pull/10998
We will introduce a small downtime when building from envoy-filter-example:master before https://github.com/envoyproxy/envoy/pull/10998 is merged.
Signed-off-by: Yuchen Dai <silentdai@gmail.com>

test: fix RawConnectionDriver

---

.devcontainer
.gitignore
http-filter-example/BUILD
http-filter-example/http_filter.cc
http-filter-example/http_filter.h
http-filter-example/http_filter_config.cc

This is also intended to be a test case for https://github.com/envoyproxy/envoy/issues/12444. cc @rgs1 
Signed-off-by: Lizan Zhou <lizan@tetrate.io>

http-filter-example: use passthrough filter lib

---

http-filter-example/http_filter_integration_test.cc

To go with https://github.com/envoyproxy/envoy/pull/13363
Signed-off-by: Matt Klein <mklein@lyft.com>

http: update header get call

---

http-filter-example/http_filter_integration_test.cc

Corresponds to https://github.com/envoyproxy/envoy/pull/15636, this was probably meant to be included with https://github.com/envoyproxy/envoy-filter-example/pull/79
Signed-off-by: Derek Argueta <deargueta@tesla.com>

test: update integration constructor

---

http-filter-example/http_filter_integration_test.cc

test fixup

---

http-filter-example/http_filter_integration_test.cc

fix test timeout

---

BUILD
echo2.cc
echo2.h
http-filter-example/BUILD
http-filter-example/http_filter.h

Signed-off-by: Yan Avlasov <yavlasov@google.com>

Changes to make example buildable with new Envoy include paths

---

http-filter-example/http_filter_integration_test.cc

Follow up to #18059.
Signed-off-by: Raul Gutierrez Segales <rgs@pinterest.com>

Rename addFilter() -> prependFilter()

---

echo2_config.cc

http: changing terminal filter type

---

.github/workflows/envoy-sync.yaml

This reverts commit 14e38bd8ab28f053f848fcd55c7164257a0e6cc4.

Revert "CUSTOM"

---

echo2_server.yaml

Fixes issue https://github.com/envoyproxy/envoy-filter-example/issues/160
Signed-off-by: Yiting Qiang <qiangyt@wxcount.com>

Fix broken echo2 sample configuration yaml

---

.github/dependabot.yml
.github/workflows/envoy-sync.yaml
.github/workflows/scorecard.yml

Signed-off-by: Matthieu MOREL <matthieu.morel35@gmail.com>

Setup OSSF workflow

---

README.md

Signed-off-by: Matthieu MOREL <matthieu.morel35@gmail.com>

add OSSF Scorecard badge
